name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: python -m unittest discover tests

    - name: Build Docker Image
      run: docker build -t devops-app:latest .

    - name: Deploy container
      run: |
        docker stop devops-container || true
        docker rm devops-container || true
        docker run -d -p 5001:5000 --name devops-container devops-app:latest

    - name: Test container HTTP
      run: |
        echo "Wait 5 seconds..."
        sleep 5
        curl -s http://localhost:5001

